Release
membraneframework/guide pull request #48
Opened 2020-12-30 16:20 UTC by mat-hek

2020-12-31 11:00 UTC, mickel8 requested changes

2020-12-31 13:27 UTC, mat-hek commented on guide/creating_app/advanced.md
> +Logging in Membrane can be configured via Elixir's `Config`. It allows to enable verbose mode and customize metadata, for example:
That's not needed. Since it's generated with `ex_doc`, the links are generated automatically.

2020-12-31 13:28 UTC, mat-hek commented on guide/creating_app/advanced.md
> +## Logging
This is elixir logger's option, so I'd redirect anyone to elixir docs ;)

2020-12-31 13:34 UTC, mat-hek commented on landing/index.html
> +</html>
Hmm, VSCode formatting automatically removes that line... is it an HTML standard?

2021-01-02 09:33 UTC, mickel8 commented on landing/index.html
> +</html>
I was thinking more about this:
https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file
but we can leave formatted version

2021-01-02 09:33 UTC, mickel8 approved these changes

2021-01-04 13:23 UTC, merged